//! Every twin's future is `Send`: the 133's async forms, the extras', `Client`'s and util's.
//! Generated by `scripts/parity.py --rust`. Do not edit: regenerate.

#![allow(dead_code, clippy::unit_arg)]

use ib_async_dx::*;
use jiff::Timestamp;

fn any<T>() -> T {
    unreachable!()
}

fn assert_send<T: Send>(_: &T) {}

fn twins(ib: &IB, client: &Client) {
    if let Ok(stream) = IB::time_range_async(Timestamp::UNIX_EPOCH, Timestamp::UNIX_EPOCH, any()) {
        assert_send(&stream);
    }
    assert_send(&ib.connect_async(any())); // connectAsync
    assert_send(&ib.qualify_contracts_async(any(), any())); // qualifyContractsAsync
    assert_send(&ib.req_tickers_async(any(), any())); // reqTickersAsync
    assert_send(&ib.what_if_order_async(any(), any())); // whatIfOrderAsync
    assert_send(&ib.req_current_time_async()); // reqCurrentTimeAsync
    assert_send(&ib.req_account_updates_async(any())); // reqAccountUpdatesAsync
    assert_send(&ib.req_account_updates_multi_async(any(), any())); // reqAccountUpdatesMultiAsync
    assert_send(&ib.account_summary_async(any())); // accountSummaryAsync
    assert_send(&ib.req_account_summary_async()); // reqAccountSummaryAsync
    assert_send(&ib.req_open_orders_async()); // reqOpenOrdersAsync
    assert_send(&ib.req_all_open_orders_async()); // reqAllOpenOrdersAsync
    assert_send(&ib.req_completed_orders_async(any())); // reqCompletedOrdersAsync
    assert_send(&ib.req_executions_async(any())); // reqExecutionsAsync
    assert_send(&ib.req_positions_async()); // reqPositionsAsync
    assert_send(&ib.req_contract_details_async(any())); // reqContractDetailsAsync
    assert_send(&ib.req_matching_symbols_async(any())); // reqMatchingSymbolsAsync
    assert_send(&ib.req_market_rule_async(any())); // reqMarketRuleAsync
    assert_send(&ib.req_historical_data_async(
        any(),
        "",
        any(),
        any(),
        any(),
        any(),
        any(),
        any(),
        any(),
        any(),
    )); // reqHistoricalDataAsync
    assert_send(&ib.req_historical_schedule_async(any(), any(), "", any())); // reqHistoricalScheduleAsync
    assert_send(&ib.req_historical_ticks_async(any(), "", "", any(), any(), any(), any(), any())); // reqHistoricalTicksAsync
    assert_send(&ib.req_head_time_stamp_async(any(), any(), any(), any())); // reqHeadTimeStampAsync
    assert_send(&ib.req_smart_components_async(any())); // reqSmartComponentsAsync
    assert_send(&ib.req_mkt_depth_exchanges_async()); // reqMktDepthExchangesAsync
    assert_send(&ib.req_histogram_data_async(any(), any(), any())); // reqHistogramDataAsync
    assert_send(&ib.req_fundamental_data_async(any(), any(), any())); // reqFundamentalDataAsync
    assert_send(&ib.req_scanner_data_async(any(), any(), any())); // reqScannerDataAsync
    assert_send(&ib.req_scanner_parameters_async()); // reqScannerParametersAsync
    assert_send(&ib.calculate_implied_volatility_async(any(), any(), any(), any())); // calculateImpliedVolatilityAsync
    assert_send(&ib.calculate_option_price_async(any(), any(), any(), any())); // calculateOptionPriceAsync
    assert_send(&ib.req_sec_def_opt_params_async(any(), any(), any(), any())); // reqSecDefOptParamsAsync
    assert_send(&ib.req_news_providers_async()); // reqNewsProvidersAsync
    assert_send(&ib.req_news_article_async(any(), any(), any())); // reqNewsArticleAsync
    assert_send(&ib.req_historical_news_async(any(), any(), "", "", any(), any())); // reqHistoricalNewsAsync
    assert_send(&ib.request_fa_async(any())); // requestFAAsync
    assert_send(&ib.get_wsh_meta_data_async()); // getWshMetaDataAsync
    assert_send(&ib.get_wsh_event_data_async(any())); // getWshEventDataAsync
    assert_send(&ib.req_user_info_async()); // reqUserInfoAsync
    assert_send(&ib.req_current_time_in_millis_async()); // reqCurrentTimeInMillisAsync
    assert_send(&ib.req_corporate_actions_async(any(), any(), any(), any())); // reqCorporateActionsAsync
    assert_send(&ib.req_spread_scan_async(any(), any(), any())); // reqSpreadScanAsync
    assert_send(&IB::wait_until_async(Timestamp::UNIX_EPOCH)); // util.waitUntilAsync
    assert_send(&client.connect_async(any(), any(), any())); // Client.connectAsync
}
